ALTER TABLE merchants ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS location_name VARCHAR(255);
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS owner_name VARCHAR(255);
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS map_thumbnail TEXT;
