ALTER TABLE menus ADD COLUMN IF NOT EXISTS cost_price NUMERIC(10,2) DEFAULT 0;
ALTER TABLE menus ADD COLUMN IF NOT EXISTS runner_fee NUMERIC(10,2) DEFAULT 0;
ALTER TABLE menus ADD COLUMN IF NOT EXISTS shooper_promo NUMERIC(10,2) DEFAULT 0;
ALTER TABLE menus ADD COLUMN IF NOT EXISTS markup_price NUMERIC(10,2) DEFAULT 0;
